export enum IncidentType {
  DELIVERY_LATE        = 'DELIVERY_LATE',
  WRONG_ADDRESS        = 'WRONG_ADDRESS',
  DAMAGED_VEHICLE      = 'DAMAGED_VEHICLE',
  MISSING_VEHICLE      = 'MISSING_VEHICLE',
  DRIVER_UNREACHABLE   = 'DRIVER_UNREACHABLE',
  UNPROFESSIONAL_DRIVER= 'UNPROFESSIONAL_DRIVER',
  WRONG_MODEL          = 'WRONG_MODEL',
  WRONG_QUANTITY       = 'WRONG_QUANTITY',
  APP_BUG              = 'APP_BUG',
  OTHER                = 'OTHER',
}